auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  join_members:
    - loki1
    - loki2
    - loki3

common:
  replication_factor: 3
  path_prefix: /loki
  ring:
    kvstore:
      store: memberlist
  storage:
    s3:
      endpoint: haproxy:9000
      bucketnames: loki-data
      access_key_id: minioadmin
      secret_access_key: minioadmin
      insecure: true
      s3forcepathstyle: true

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: s3

ruler:
  storage:
    type: s3
    s3:
      endpoint: haproxy:9000
      bucketnames: loki-data
      access_key_id: minioadmin
      secret_access_key: minioadmin
      insecure: true
      s3forcepathstyle: true
  rule_path: /tmp/rules
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: memberlist
